#!/usr/bin/env bash
# subdomain www points to the load-balancer IP (lb-01).
# script that will display information about subdomains.

sub_domains=( "www" "lb-01" "web-01" "web-02" )

details () {
	domain=$1
	subdomain=$2

	dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " }; { print "The subdomain " s " is a " $4 " record and points to " $5 }'
}

if [ $# -eq 1 ]; then
	domain="$1"
	for i in "${sub_domains[@]}"
	do
		details "$domain" "$i"
	done
elif [ $# -eq 2 ]; then
	domain="$1"
	subdomain="$2"
	details "$domain" "$subdomain"
fi
