#!/usr/bin/env bash
# Redirection script

apt-get update -y
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root    /var/www/html;
    index   index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 http://juliusdgenius-alx.tech/;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
