#!/usr/bin/env bash
# Installs, configures, and starts the server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html /var/www/error
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/error/404.html
# the server's configuration
echo "server {
   listen 80 default_server;
   listen [::]:80 default_server;
   root /var/www/html;
   index index.html index.htm index.nginx-debian.html;
   server_name _;
   location /redirect_me {
       return 301 http://juliusdgenius-alx.tech/;
   }

   error_page 404 /404.html;
   location = /404 {
   root /var/www/error;
   internal;
   }
}" > /etc/nginx/sites-enabled/default
service nginx restart
