#!/usr/bin/env bash
# Use trap and creates PID file in /var/run directory

delete() {
    rm /var/run/myscript.pid
        exit
}

echo "$$" > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'echo "I hate the kill command" && delete' SIGTERM
    trap 'terminator' SIGQUITgit 
done
