#!/usr/bin/env bash
# A bash script that displays:
# The content of the current directory in a list format
# Where only the part of the name after the first dash
# is displayed

current_dir=(ls)
for i in "${current_dir[@]}"; do
    $i | cut -d '-' -f 2
done
