#!/usr/bin/env bash
# A bash script that gives information about a file: school

current_dir=( * )
found=false
file="school"

if [ -e $file ]; then
    echo "$file file exists"
    if [ -s $file ]; then
        echo "$file file is not empty"
    else
        echo "$file is empty"
    fi

    if [ -f $file ]; then
        echo "$file is a regular file"
    fi
else
    echo "$file does not exist"
fi
