#!/usr/bin/env bash
#Fixes container so that Nginx is running as the nginx user.

# Below command will set a user in the config file
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# set port to 8080 instead of 80
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Grant read/write permissions of the config file to owner
chmod 644 /etc/nginx/nginx.conf

# Kill apache process if running as it can interfer with nginx
pkill apache2

# Start nginx with the new nginx user
sudo -u nginx service nginx start
