#!/usr/bin/env bash
# $OpenBSD: sshd_config.v 1.103 2018/04/09 20:41:22 tj Exp $

# This is the send server system-wide configuration file. see
# sshd_config(5) for more information.

# This sshd was compiled with PATH=/usr/bin:/bin:/usr/sbin:/sbin

# This strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented. Uncommented options override the default value.

Include /etc/ssh/sshd_config.d/*.conf

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#Hostkey /etc/ssh_host-rsa_key
3hostkey /etc/ssh/ssh-host_ecdsa_key
#Hostkey /etc/ssh/ssh_host_ed25519_key

# Ciphers and Keying
#ReKeyLimit default none

# Loggong
#SyslogFacilit AUTH
#LogLevel   INFO

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibited-password
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

#PubKeyAuthentication yes

# Expect .ssh/authorized_key2 to be disregaerded by default in future.
#AuthorizedKeyFile  .ssh/authorized_keys .ssh/authorized_keys2

#AuthorizedPrincipalsFile none

#AuthorizedKeysCommand none
#AuthorizedKeysCommandUser nobody

# For this to work you will also need host keys in /etc/ssh/ssh_known_host>
#HostbasedAuthentication
#ignoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shodt files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
PasswordAuthentication no
#PermitEmptyPasswords no

# Kerberos options
#KerberosAuthentication no
#KerberosOrLocalPasswd yes
#KerberosTicketCleanup yes
#kerberosGetAFSToken no

# GSSAPI options
#GSSAPIAuthentication no
#GSSAPICleanupCredentials yes
#GSSAPIStrictAcceptorCheck yes
#GSSAPIKeyExchange no
# Set this to 'yes' to enable PAM authentication, account processing,
# and session processing. If this is enabled, PAM authentication will
# be allowed through the ChallengeResponseAuthentication and
# PasswordAuthentication. Depending on your PAM configuration, PAM
# authentication via ChallengResponseAuthentication may bypass the
# setting of "PermitRootLogin without-password."
#if you just want the PAM account and session checks to run without
# PAM authentication, then enable this but set PasswordAuthentication
# and ChallengeResponseAuthentication to 'no'.
UsePam yes

#AllowAgentForwarding yes
#AllowTcpForwarding yes
#GatewayPorts no
X11Forwarding yes
#X11DisplayOffset 10
#X11UseLocalhost yes
#PermitTTY yes
PrintMotd no
#PrintLastLog yes
#TCPKeepAlive yes
#PermitUserEnvironment no
#Compression delayed
#ClientAliveInterval 0
#ClientALiveCountMax 3
#UseDNS no
#ChrootDirectory none
#VersionAddendum none

# no default banner path
#Banner none

# Allow client to pass locale environment variables
Accept LANG LC_*

# override default of no subsystems
Subsystem   sftp    /usr/lib/openssh/sftp-server

# Example of overriding settings on a per-user basis
#Match User anoncvs
#   X11Forwarding no
#   AllowTcpForwarding no
#   PermitTTY no
#   ForceCommand cvs server
